FROM ruby:3.1.4

RUN apt-get update -qq && \
    apt-get install -y --no-install-recommends \
      build-essential default-libmysqlclient-dev nodejs imagemagick libmagickwand-dev && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY Gemfile ./
RUN bundle install --jobs 4

COPY . .

CMD ["bundle", "exec", "rspec"]
